// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc4TIXjT7HFL9NaR7pWOB6w4eRBXE5Q8A',
    appId: '1:908767967330:web:f66c5dd73c3cd22904b93b',
    messagingSenderId: '908767967330',
    projectId: 'hangman-ieee-intromeet-2023',
    authDomain: 'hangman-ieee-intromeet-2023.firebaseapp.com',
    storageBucket: 'hangman-ieee-intromeet-2023.appspot.com',
    measurementId: 'G-8V07Z1HHJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5MmEV8FLA_82na5Yr4d4xwkhOtHiPX7A',
    appId: '1:908767967330:android:c2f2823c8f4e902504b93b',
    messagingSenderId: '908767967330',
    projectId: 'hangman-ieee-intromeet-2023',
    storageBucket: 'hangman-ieee-intromeet-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJFzBzZfSPT81C7_-RQOg94If4gLcVRc8',
    appId: '1:908767967330:ios:459b59c5bdb0addb04b93b',
    messagingSenderId: '908767967330',
    projectId: 'hangman-ieee-intromeet-2023',
    storageBucket: 'hangman-ieee-intromeet-2023.appspot.com',
    iosBundleId: 'com.example.hangmanIeeeIntromeet2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJFzBzZfSPT81C7_-RQOg94If4gLcVRc8',
    appId: '1:908767967330:ios:39ced146f80b999a04b93b',
    messagingSenderId: '908767967330',
    projectId: 'hangman-ieee-intromeet-2023',
    storageBucket: 'hangman-ieee-intromeet-2023.appspot.com',
    iosBundleId: 'com.example.hangmanIeeeIntromeet2023.RunnerTests',
  );
}
